version: '3'
services:
  app:
    container_name: docker-node-mongo
    build: .
    ports:
      - '4215:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    
    volumes: ['./:/usr/src/app']

    ports:
      - '27017:27017'